### ISSUE TITLE
Cannot build PyGObject

### ISSUE THREAD

**Issue by rishabhp** [EricssonResearch/openwebrtc-build-scripts#31]
When the build scripts come down to building pygobject (Mac OSX Yosemite), it ends up with this error:

```bash
Marking sources installed in pygobject
Already on 'master'
[master 40e086e] tag file identifying the build script that installed the sources
 1 file changed, 1 insertion(+)
 create mode 100644 .sources_installed_tag_file.txt
Switched to branch 'x86_64-apple-darwin'
lcov not installed, not enabling code coverage
/Users/rishabhpugalia/.openwebrtc/bin/gnome-autogen.sh
 checking for autoconf >= 2.53...
   testing autoconf2.50...  not found.
  testing autoconf...  found 2.68
 checking for automake >= 1.9...
   testing automake-1.13...  found 1.13.1
 checking for libtool >= 1.4.3...
   testing libtoolize...  found 2.4.2
 using /Users/rishabhpugalia/.openwebrtc/bin/pkg-config for pkg-config
  Checking for required M4 macros...
   gnome-compiler-flags.m4 not found
***Error***: some autoconf macros required to build pygobject
  were not found in your aclocal path, or some forbidden
  macros were found.  Perhaps you need to adjust your
  ACLOCAL_FLAGS?

./build-pygobject.sh -- Could not build pygobject.
Failed building...pygobject
```

Any idea what could be done ?

**Comment by rishabhp** [comment]
Installed `gnome-common` and `glib` using `brew` and the entire `bootstrap` script executed well.

**Comment by superdump** [comment]
@rishabhp You should not need to install anything with brew. We build glib and gnome-common in bootstrap. If building pygobject failed because of glib/gnome-common then they must not have built properly. Building them using brew instead is not a support fix and you may encounter other issues as a consequence because your bootstrap is incomplete/broken.

**Comment by rishabhp** [comment]
I think you're right, also got to know that from other people. But then the only problem is, before installing with `brew` I just could not fix it and I'm not sure what was wrong, nor anyone on IRC could help me out. They suggested me to use Cerbero instead and someone had the same issue with that too.

I wonder if you guys should consider looking into a non-plain installation of Mac and trying to build it there instead of trying the build process on a simple plain Mac ? Again, really not sure.
