### ISSUE TITLE
update bash scripts to fix openSSL version update

### ISSUE THREAD

**Issue by michael-tourneur** [EricssonResearch/openwebrtc-build-scripts#37]
Recently contriibutors has updated openSSL version but forgot to update two scripts.

Please to update OPENSSL_VERSION variable to 1.0.2 on files:
build-gst-plugins-bad.sh
build-libsrtp.sh

**Comment by superdump** [comment]
You're welcome to make a pull request if you have a moment.

**Comment by superdump** [comment]
@stefhak I was just going to merge this. Do you have a problem with me doing that and then you can rebase your changes on top of it?

**Comment by superdump** [comment]
I've merged @michael-tourneur 's pull request. Thanks for the contribution. :smile:
